import BeeqSetup from './beeq';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'BEEQ + Next.js',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BeeqSetup>{children}</BeeqSetup>
      </body>
    </html>
  );
}